
title: Sideproject
desctiption: 
permalink: ':title/'

markdown: kramdown
baseurl: "/misc"


sass:
    style: compressed

  
  
  
collections: 
     travel:
        output: true
        permalink: /travel/:path/
     food:
        output: true
        permalink: /food/:path/
     photography:
        output: true
        permalink: /photography/:path/
    
    

#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

highlight: rouge


# Tracker
analytics: UA-83979019-1

# Comments
disqus-shortname: webjeda-demo

# Contact form
# Go to https://getsimpleform.com and get a API token by signing up with your email and enter that here
api-token:   

include: [_pages]
version: 0.8

gems: [jekyll-paginate, jekyll-seo-tag]